# Generated by Django 4.0 on 2021-12-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=5000)),
                ('from_id', models.CharField(max_length=10)),
                ('to_id', models.CharField(max_length=10)),
                ('result', models.CharField(max_length=5000)),
            ],
        ),
    ]
