# Generated by Django 4.0 on 2021-12-27 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translateapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translate',
            old_name='from_id',
            new_name='from_lang',
        ),
    ]
