# Generated by Django 4.0 on 2021-12-27 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translateapi', '0002_rename_from_id_translate_from_lang'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translate',
            old_name='to_id',
            new_name='to_lang',
        ),
    ]
