version: "3.0"
services:
    bot:
        build:
            context: .
            dockerfile: Dockerfile
        stop_signal: SIGINT
        restart: unless-stopped
        env_file:
            - .env
